=== jonashammerschmidt/Contractor/Contractor.CLI/contractor.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" vc:minVersion="1.1" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning">
  <xs:element name="Contractor">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Paths">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="BackendDestinationFolder" type="xs:string" />
              <xs:element name="DbDestinationFolder" type="xs:string" />
              <xs:element name="FrontendDestinationFolder" type="xs:string" />
              <xs:element name="ProjectName" type="xs:string" />
              <xs:element name="DbProjectName" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Replacements">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" maxOccurs="unbounded" name="Replacement">
                <xs:complexType>
                  <xs:attribute name="pattern" type="xs:string" use="required" />
                  <xs:attribute name="ReplaceWith" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Modules">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="Module">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Entity">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element minOccurs="0" maxOccurs="unbounded" name="Property">
                            <xs:complexType>
                              <xs:attribute name="name" type="xs:string" use="required" />
                              <xs:attribute name="type" type="xs:string" use="required" />
                              <xs:attribute name="optional" type="xs:boolean" use="optional" />
                            </xs:complexType>
                          </xs:element>
                          <xs:element minOccurs="0" maxOccurs="unbounded" name="Relation1ToN">
                            <xs:complexType>
                              <xs:attribute name="entityNameFrom" type="xs:string" use="required" />
                              <xs:attribute name="propertyNameFrom" type="xs:string" use="optional" />
                              <xs:attribute name="PropertyNameTo" type="xs:string" use="optional" />
                              <xs:attribute name="optional" type="xs:boolean" use="optional" />
                            </xs:complexType>
                          </xs:element>
                          <xs:element minOccurs="0" maxOccurs="unbounded" name="Relation1To1">
                            <xs:complexType>
                              <xs:attribute name="entityNameFrom" type="xs:string" use="required" />
                              <xs:attribute name="propertyNameFrom" type="xs:string" use="optional" />
                              <xs:attribute name="PropertyNameTo" type="xs:string" use="optional" />
                              <xs:attribute name="optional" type="xs:boolean" use="optional" />
                            </xs:complexType>
                          </xs:element>
                          <xs:element minOccurs="0" maxOccurs="unbounded" name="Index">
                            <xs:complexType>
                              <xs:attribute name="property" type="xs:string" use="required" />
                              <xs:attribute name="clustered" type="xs:boolean" use="optional" />
                              <xs:attribute name="unique" type="xs:boolean" use="optional" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required" />
                        <xs:attribute name="namePlural" type="xs:string" use="required" />
                        <xs:attribute name="scopeEntityName" type="xs:string" use="optional" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== jonashammerschmidt/Contractor/contractor.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Contractor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="contractor.xsd">
    <Paths>
        <BackendDestinationFolder>FullstackTemplate\Krz.FullstackTemplate.Backends\Krz.FullstackTemplate.Backend.Core</BackendDestinationFolder>
        <DbDestinationFolder>FullstackTemplate\Krz.FullstackTemplate.Databases\Krz.FullstackTemplate.Database.Core</DbDestinationFolder>
        <FrontendDestinationFolder>FullstackTemplate\Krz.FullstackTemplate.Frontends\Krz.FullstackTemplate.Web.Core</FrontendDestinationFolder>
        <ProjectName>Krz.FullstackTemplate.Backend.Core</ProjectName>
        <DbProjectName>Krz.FullstackTemplate.Database.Core</DbProjectName>
    </Paths>
    <Replacements>
        <Replacement pattern="app-search-dropdown" ReplaceWith="search-dropdown" />
        <Replacement pattern="app-table-filter-bar" ReplaceWith="table-filter-bar" />
        <Replacement pattern="src/app/components/ui/dropdown-data-source/dropdown-pagination-data-source" ReplaceWith="@krz/material" />
        <Replacement pattern="src/app/components/ui/search-dropdown/search-dropdown.module" ReplaceWith="@krz/material" />
        <Replacement pattern="src/app/components/ui/table-filter-bar/table-filter-bar.module" ReplaceWith="@krz/material" />
        <Replacement pattern="src/app/services/backend/pagination/i-paged-result" ReplaceWith="@krz/material" />
        <Replacement pattern="src/app/services/backend/pagination/i-pagination-options" ReplaceWith="@krz/material" />
        <Replacement pattern="src/app/services/backend/pagination/pagination.data-source" ReplaceWith="@krz/material" />
        <Replacement pattern="Contract.Architecture.Backend.Common" ReplaceWith="Krz.FullstackTemplate.Backend.Common" />
    </Replacements>
    <Modules>
        <Module name="Bankwesen">
            <Entity name="SchöneBank" namePlural="SchöneBänke" scopeEntityName="Mandant">
                <Property name="Bezeichnung" type="string:256" />
                <Property name="IsPleite" type="bool" />
                <Property name="LegacyBezeichnung" type="string:256" isOptional="true" />
                <Property name="LegacyIsPleite" type="bool" isOptional="true" />
                <Index property="Bezeichnung" clustered="true" unique="true" />
            </Entity>
        </Module> 
        <Module name="Kundenstamm">
            <Entity name="Kunde" namePlural="Kunden" scopeEntityName="Mandant">
                <Property name="Bezeichnung" type="string:256" />
                <Property name="Kundennummer" type="int" />
                <Property name="KundennummerLegacy" type="int" isOptional="true" />
                <Relation1ToN entityNameFrom="SchöneBank" propertyNameFrom="MeineBank" PropertyNameTo="MeineKonten" />
                <Relation1To1 entityNameFrom="SchöneBank" propertyNameFrom="BäckupBank" PropertyNameTo="BäckupKunde" isOptional="true" />
                <Index property="Bezeichnung" clustered="true" />
            </Entity>
        </Module>
        <Module name="Kontoführung">
            <Entity name="Konto" namePlural="Konten" scopeEntityName="Mandant">
                <Property name="Bezeichnung" type="string:256" />
                <Property name="SystemKontoId" type="Guid" />
                <Property name="Balance" type="Double" />
                <Property name="EröffnetAm" type="DateTime" />
                <Property name="LegacySystemKontoId" type="Guid" isOptional="true"/>
                <Property name="LegacyBalance" type="Double" isOptional="true" />
                <Property name="LegacyEröffnetAm" type="DateTime" isOptional="true" />
                <Relation1ToN entityNameFrom="Kunde" propertyNameFrom="MeinKunde" PropertyNameTo="MeinKonten" />
                <Relation1To1 entityNameFrom="Kunde" propertyNameFrom="BäckupKunde" PropertyNameTo="BäckupKonto" isOptional="true" />
                <Index property="Bezeichnung,SystemKontoId" unique="true" />
            </Entity>
        </Module>
    </Modules>
</Contractor>

=== jonashammerschmidt/Contractor/Contractor.CLI/contractor.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Contractor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="contractor.xsd">
  <Paths>
    <BackendDestinationFolder>..\..\..\..\FullstackTemplate\Krz.FullstackTemplate.Backends\Krz.FullstackTemplate.Backend.Core</BackendDestinationFolder>
    <DbDestinationFolder>..\..\..\..\FullstackTemplate\Krz.FullstackTemplate.Databases\Krz.FullstackTemplate.Database.Core</DbDestinationFolder>
    <FrontendDestinationFolder>..\..\..\..\FullstackTemplate\Krz.FullstackTemplate.Frontends\Krz.FullstackTemplate.Web.Core</FrontendDestinationFolder>
    <ProjectName>Krz.FullstackTemplate.Backend.Core</ProjectName>
    <DbProjectName>Krz.FullstackTemplate.Database.Core</DbProjectName>
    <DbContextName>FullstackTemplateCoreDbContext</DbContextName>
  </Paths>
  <Replacements>
    <Replacement pattern="app-search-dropdown" replaceWith="search-dropdown" />
    <Replacement pattern="app-table-filter-bar" replaceWith="table-filter-bar" />
    <Replacement pattern="src/app/components/ui/dropdown-data-source/dropdown-pagination-data-source" replaceWith="@krz/material" />
    <Replacement pattern="src/app/components/ui/search-dropdown/search-dropdown.module" replaceWith="@krz/material" />
    <Replacement pattern="src/app/components/ui/table-filter-bar/table-filter-bar.module" replaceWith="@krz/material" />
    <Replacement pattern="src/app/services/backend/pagination/i-paged-result" replaceWith="@krz/material" />
    <Replacement pattern="src/app/services/backend/pagination/i-pagination-options" replaceWith="@krz/material" />
    <Replacement pattern="src/app/services/backend/pagination/pagination.data-source" replaceWith="@krz/material" />
    <Replacement pattern="Contract.Architecture.Backend.Common" replaceWith="Krz.FullstackTemplate.Backend.Common" />
  </Replacements>
  <Modules>
    <Module name="MandantenTrennung" skip="true">
      <Entity name="Mandant" namePlural="Mandanten" skip="true">
        <Property name="Name" type="String:256" />
      </Entity>
    </Module>
    <Module name="Bankwesen">
      <Entity name="SchöneBank" namePlural="SchöneBänke" scopeEntityName="Mandant">
        <Property name="Name" type="String:256" />
        <Property name="IsPleite" type="Boolean" />
        <Property name="LegacyBezeichnung" type="String:256" optional="true" />
        <Property name="LegacyIsPleite" type="Boolean" optional="true" />
        <Index property="Name" clustered="true" unique="true" />
      </Entity>
    </Module>
    <Module name="Kundenstamm">
      <Entity name="Kunde" namePlural="Kunden" scopeEntityName="Mandant">
        <Property name="VorUndNachname" type="String:256" displayProperty="true" />
        <Property name="Kundennummer" type="Integer" />
        <Property name="KundennummerLegacy" type="Integer" optional="true" />
        <Relation1ToN entityNameFrom="SchöneBank" propertyNameFrom="MeineBank" propertyNameTo="MeineKonten" />
        <Relation1To1 entityNameFrom="SchöneBank" propertyNameFrom="LieblingsBank" propertyNameTo="LieblingsKunde"/>
        <Index property="VorUndNachname" clustered="true" />
      </Entity>
    </Module>
    <Module name="Kontoführung">
      <Entity name="Konto" namePlural="Konten" scopeEntityName="Mandant">
        <Property name="Bezeichnung" type="String:256" />
        <Property name="SystemKontoId" type="Guid" />
        <Property name="Balance" type="Double" />
        <Property name="EröffnetAm" type="DateTime" />
        <Property name="LegacySystemKontoId" type="Guid" optional="true"/>
        <Property name="LegacyBalance" type="Double" optional="true" />
        <Property name="LegacyEröffnetAm" type="DateTime" optional="true" />
        <Relation1ToN entityNameFrom="Kunde" optional="true" />
        <Relation1To1 entityNameFrom="Kunde" propertyNameFrom="BäckupKunde" propertyNameTo="BäckupKonto" optional="true" />
        <Index property="Bezeichnung,SystemKontoId" unique="true" />
      </Entity>
    </Module>
  </Modules>
</Contractor>

=== jonashammerschmidt/Contractor/Contractor.XML/contractor.xml
<?xml version="1.0" encoding="UTF-8"?>
<Contractor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XSD/contractor.xsd">
  <Paths>
    <BackendDestinationFolder>..\FullstackTemplate\Krz.FullstackTemplate.Backends\Krz.FullstackTemplate.Backend.Core</BackendDestinationFolder>
    <DbDestinationFolder>..\FullstackTemplate\Krz.FullstackTemplate.Databases\Krz.FullstackTemplate.Database.Core</DbDestinationFolder>
    <FrontendDestinationFolder>..\FullstackTemplate\Krz.FullstackTemplate.Frontends\Krz.FullstackTemplate.Web.Core</FrontendDestinationFolder>
    <ProjectName>Krz.FullstackTemplate.Backend.Core</ProjectName>
    <DbProjectName>Krz.FullstackTemplate.Database.Core</DbProjectName>
    <DbContextName>FullstackTemplateCoreDbContext</DbContextName>
  </Paths>
  <Replacements>
    <Replacement pattern="app-search-dropdown" replaceWith="search-dropdown" />
    <Replacement pattern="app-table-filter-bar" replaceWith="table-filter-bar" />
    <Replacement pattern="src/app/components/ui/dropdown-data-source/dropdown-pagination-data-source" replaceWith="@krz/material" />
    <Replacement pattern="src/app/components/ui/search-dropdown/search-dropdown.module" replaceWith="@krz/material" />
    <Replacement pattern="src/app/components/ui/table-filter-bar/table-filter-bar.module" replaceWith="@krz/material" />
    <Replacement pattern="src/app/components/ui/file-picker/file-picker.module" replaceWith="@krz/material" />
    <Replacement pattern="src/app/services/backend/pagination/i-paged-result" replaceWith="@krz/material" />
    <Replacement pattern="src/app/services/backend/pagination/i-pagination-options" replaceWith="@krz/material" />
    <Replacement pattern="src/app/services/backend/pagination/pagination.data-source" replaceWith="@krz/material" />
    <Replacement pattern="Contract.Architecture.Backend.Common" replaceWith="Krz.FullstackTemplate.Backend.Common" />
  </Replacements>
  <Includes>
    <Include src="./contractor-mandanten.xml" />
  </Includes>
  <Modules>
    <Module name="Bankwesen">
      <Entity name="Konto" namePlural="Konten" scopeEntityName="Mandant">
        <Property name="Bezeichnung" type="String:256" />
        <Relation1ToN entityNameFrom="Kunde" onDelete="Cascade" />
        <Relation1To1 entityNameFrom="Kunde" propertyNameFrom="BäckupKunde" propertyNameTo="BäckupKonto" optional="true" onDelete="ClientSetNull" />
        <Index property="Bezeichnung" unique="true" />
      </Entity>
      <Entity name="SchöneBank" namePlural="SchöneBänke" scopeEntityName="Mandant">
        <Property name="Name" type="String:256" />
        <Index property="Name,MandantId" clustered="true" unique="true" />
      </Entity>
    </Module>
    <Module name="Kundenstamm">
      <Entity name="Kunde" namePlural="Kunden">
        <Property name="VorUndNachname" type="String:256" displayProperty="true" />
        <Relation1ToN entityNameFrom="SchöneBank" propertyNameFrom="MeineBank" propertyNameTo="MeineKunden" optional="true" />
        <Relation1To1 entityNameFrom="SchöneBank" propertyNameFrom="LieblingsBank" propertyNameTo="LieblingsKunde" />
        <Index property="VorUndNachname" clustered="true" />
      </Entity>
    </Module>
    <Module name="PropertyTesting">
      <Entity name="PropertyTest" namePlural="PropertyTests">
        <Property name="TestString" type="String:256" />
        <Property name="TestGuid" type="Guid" />
        <Property name="TestDouble" type="Double" />
        <Property name="TestBoolean" type="Boolean" />
        <Property name="TestInteger" type="Integer" />
        <Property name="TestDateTime" type="DateTime" />
        <Property name="TestByteArray" type="ByteArray" />
        <Property name="OptionalTestString" type="String:256" optional="true" />
        <Property name="OptionalTestGuid" type="Guid" optional="true" />
        <Property name="OptionalTestDouble" type="Double" optional="true" />
        <Property name="OptionalTestBöüleänß" type="Boolean" optional="true" />
        <Property name="OptionalTestInteger" type="Integer" optional="true" />
        <Property name="OptionalTestByteArray" type="ByteArray" optional="true" />
        <Property name="OptionalTestDateTime" type="DateTime" optional="true" />
        <Index property="TestInteger" unique="true" where="[TestInteger] > 0" />
        <Check name="TestDoubleGroesserNull" query="[TestDouble] > 0" />
      </Entity>
    </Module>
  </Modules>
</Contractor>
